# Do not use Kong Ingress Controller
ingressController:
 enabled: false
  
image:
 repository: kong
 tag: "3.9.0"
  
# Mount the secret created earlier
secretVolumes:
 - kong-cluster-cert
  
env:
 # data_plane nodes do not have a database
 role: data_plane
 database: "off"
  
 # Tell the data plane how to connect to the control plane
 cluster_control_plane: kong-cp-kong-cluster.kong.svc.cluster.local:8005
  
 # Configure control plane / data plane authentication
 lua_ssl_trusted_certificate: /etc/secrets/kong-cluster-cert/tls.crt
 cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
 cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  
# Enterprise functionality
enterprise:
 enabled: false
  
# The data plane handles proxy traffic only
proxy:
 enabled: true
  
# These roles are served by the kong-cp deployment
admin:
 enabled: false
  
manager:
 enabled: false

# Resource Requests and Limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Autoscaling Configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60